In [1]:
import pandas as pd

In [5]:
pd.__version__

'2.2.2'

#1 .Data Frame

---

In [6]:
# create -- Dataframe -> Data ->Table
df = pd.DataFrame([1,2,3])
print(df)

   0
0  1
1  2
2  3

In [7]:
df=pd.DataFrame([1,2,3], columns=['col_Name'])
print(df)

   col_Name
0         1
1         2
2         3

In [8]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [9]:
data={
    "Name":["Omkar","Yash","Atul"],
    "Age":[21,21,30],
    "Salary": [9000,4000,29000]
}

In [10]:
df=pd.DataFrame(data)
print(df)

    Name  Age  Salary
0  Omkar   21    9000
1   Yash   21    4000
2   Atul   30   29000

In [11]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

# 2.Understanding Data *frame*

In [12]:
df.head(2) #top rows

    Name  Age  Salary
0  Omkar   21    9000
1   Yash   21    4000

In [13]:
df.tail(2)  #Last rows

   Name  Age  Salary
1  Yash   21    4000
2  Atul   30   29000

In [14]:
df.shape

(3, 3)

In [15]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [16]:
df.rename(columns={'Month Salary':'Salary'},inplace=True)

In [17]:
df

    Name  Age  Salary
0  Omkar   21    9000
1   Yash   21    4000
2   Atul   30   29000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [19]:
df.describe()   #Values program

             Age        Salary
count   3.000000      3.000000
mean   24.000000  14000.000000
std     5.196152  13228.756555
min    21.000000   4000.000000
25%    21.000000   6500.000000
50%    21.000000   9000.000000
75%    25.500000  19000.000000
max    30.000000  29000.000000

#3 .Save and load data from CSV

---

In [20]:
df.to_csv('data.csv',index=False) #save data

In [21]:
pd.read_csv('data.csv') #Load Data #import

    Name  Age  Salary
0  Omkar   21    9000
1   Yash   21    4000
2   Atul   30   29000

# 4.Rows & columns = selection

---

In [22]:
#select column
df[["Name"]]    #Single col

    Name
0  Omkar
1   Yash
2   Atul

In [23]:
df[["Name","Salary"]]

    Name  Salary
0  Omkar    9000
1   Yash    4000
2   Atul   29000

In [24]:
#select row
df.loc[df.Name=='Omkar']

    Name  Age  Salary
0  Omkar   21    9000

In [25]:
df.loc[(df.Name=="Omkar") & (df['Salary'] >=6000)]

    Name  Age  Salary
0  Omkar   21    9000

In [26]:
#iloc -index based
df.iloc[0]
df.iloc[0:3]

    Name  Age  Salary
0  Omkar   21    9000
1   Yash   21    4000
2   Atul   30   29000


# 5.Filter dataframe
---

In [27]:
df_age_filter= df[df['Age'] >20]

In [28]:
df_age_filter

    Name  Age  Salary
0  Omkar   21    9000
1   Yash   21    4000
2   Atul   30   29000

In [29]:
df[(df['Age'] >= 18 ) & (df["Salary"] >= 9000)]

    Name  Age  Salary
0  Omkar   21    9000
2   Atul   30   29000

In [30]:
df.where(df["Age"] >= 25)

   Name   Age   Salary
0   NaN   NaN      NaN
1   NaN   NaN      NaN
2  Atul  30.0  29000.0

In [31]:
df.where(df["Age"] >= 25,other ="Not Eligible")

           Name           Age        Salary
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2          Atul            30         29000

# 6.Rows and Columns -operation (ADD,UPDATE,DELETE)

---

In [32]:
#Add new column

df['team']=['CEO',"HR","DA"]
df

    Name  Age  Salary team
0  Omkar   21    9000  CEO
1   Yash   21    4000   HR
2   Atul   30   29000   DA

In [33]:
df['Bonus'] = df['Salary'] * 0.2
df

    Name  Age  Salary team   Bonus
0  Omkar   21    9000  CEO  1800.0
1   Yash   21    4000   HR   800.0
2   Atul   30   29000   DA  5800.0

In [34]:
#add new row
df.loc[len(df)]=['ABC',21,21000,'IT',2000]
df

    Name  Age  Salary team   Bonus
0  Omkar   21    9000  CEO  1800.0
1   Yash   21    4000   HR   800.0
2   Atul   30   29000   DA  5800.0
3    ABC   21   21000   IT  2000.0

In [35]:
len(df)

4

In [36]:
#update valus
df.loc[0,'Salary'] = 45000
df

    Name  Age  Salary team   Bonus
0  Omkar   21   45000  CEO  1800.0
1   Yash   21    4000   HR   800.0
2   Atul   30   29000   DA  5800.0
3    ABC   21   21000   IT  2000.0

In [37]:
#update value - using column value
df.loc[df.Name =="Yash",'Salary'] =9000
df

    Name  Age  Salary team   Bonus
0  Omkar   21   45000  CEO  1800.0
1   Yash   21    9000   HR   800.0
2   Atul   30   29000   DA  5800.0
3    ABC   21   21000   IT  2000.0

In [38]:
#delete value - row and column values
df=df.drop(df[df.Name=="ABC"].index)
df  #drop row axis=0

    Name  Age  Salary team   Bonus
0  Omkar   21   45000  CEO  1800.0
1   Yash   21    9000   HR   800.0
2   Atul   30   29000   DA  5800.0

In [39]:
#df.drop('Bonus',axis=1,inplace=True)    #drop column

In [40]:
df

    Name  Age  Salary team   Bonus
0  Omkar   21   45000  CEO  1800.0
1   Yash   21    9000   HR   800.0
2   Atul   30   29000   DA  5800.0

In [41]:
#df.drop(['Bonus',"Team"],axis=1,inplace=True)

In [42]:
df

    Name  Age  Salary team   Bonus
0  Omkar   21   45000  CEO  1800.0
1   Yash   21    9000   HR   800.0
2   Atul   30   29000   DA  5800.0

In [43]:
# Sort
df.sort_values(by="Salary",ascending=False)      # ascending order

    Name  Age  Salary team   Bonus
0  Omkar   21   45000  CEO  1800.0
2   Atul   30   29000   DA  5800.0
1   Yash   21    9000   HR   800.0

#7 .Working with date values

---

In [44]:
df['DOJ']=['2026-01-01','2026-01-15', '2026-03-27']
df

    Name  Age  Salary team   Bonus         DOJ
0  Omkar   21   45000  CEO  1800.0  2026-01-01
1   Yash   21    9000   HR   800.0  2026-01-15
2   Atul   30   29000   DA  5800.0  2026-03-27

In [45]:
df['DOJ'].dtype

dtype('O')

In [46]:
import pandas as pd

data={
    "Name":["Omkar","Yash","Atul"],
    "Age":[21,21,30],
    "Salary": [9000,4000,29000]
}
df=pd.DataFrame(data)
df['team']=['CEO',"HR","DA"]
df['Bonus'] = df['Salary'] * 0.2
df['DOJ']=['2026-01-01','2026-01-15', '2026-03-27']



df['DOJ']=pd.to_datetime(df['DOJ'])

In [47]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [48]:
df1 =df
df

    Name  Age  Salary team   Bonus        DOJ
0  Omkar   21    9000  CEO  1800.0 2026-01-01
1   Yash   21    4000   HR   800.0 2026-01-15
2   Atul   30   29000   DA  5800.0 2026-03-27

In [49]:
df1['DOJ2']=['2026-01-01','2026-01-15', '2026-03-27']
df1

    Name  Age  Salary team   Bonus        DOJ        DOJ2
0  Omkar   21    9000  CEO  1800.0 2026-01-01  2026-01-01
1   Yash   21    4000   HR   800.0 2026-01-15  2026-01-15
2   Atul   30   29000   DA  5800.0 2026-03-27  2026-03-27

In [50]:
df1['DOJ2'].dtype

dtype('O')

In [52]:
df1['DOJ2']=pd.to_datetime(df1['DOJ2'] ,format ='%Y-%m-%d')

In [53]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [56]:
df1=df1.drop('DOJ2',axis=1)
df1

    Name  Age  Salary team   Bonus        DOJ
0  Omkar   21    9000  CEO  1800.0 2026-01-01
1   Yash   21    4000   HR   800.0 2026-01-15
2   Atul   30   29000   DA  5800.0 2026-03-27

In [57]:
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0    Thursday
1    Thursday
2      Friday
Name: DOJ, dtype: object

In [74]:
df['Month'] = df['DOJ'].dt.month

In [59]:
df['DOJ'] + pd.Timedelta(days=90)

0   2026-04-01
1   2026-04-15
2   2026-06-25
Name: DOJ, dtype: datetime64[ns]

#8 . Handling Missing Values

In [60]:
df

    Name  Age  Salary team   Bonus        DOJ
0  Omkar   21    9000  CEO  1800.0 2026-01-01
1   Yash   21    4000   HR   800.0 2026-01-15
2   Atul   30   29000   DA  5800.0 2026-03-27

In [61]:
df.isnull()

    Name    Age  Salary   team  Bonus    DOJ
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False

In [62]:
import numpy as np

In [63]:
df.loc[df.Name=="Omkar","Salary"]==np.nan

0    False
Name: Salary, dtype: bool

In [64]:
df.isnull()

    Name    Age  Salary   team  Bonus    DOJ
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False

In [65]:
df.isnull().sum()

Name      0
Age       0
Salary    0
team      0
Bonus     0
DOJ       0
dtype: int64

#9.Aggregation and Group by

---

In [72]:
df['Salary'].value_counts()   #frequency of value

Salary
9000     1
4000     1
29000    1
Name: count, dtype: int64

In [71]:
df[df['Salary']==1].value_counts()

Series([], Name: count, dtype: int64)

In [78]:
#Group By

df.groupby('Month')['Salary'].mean()   # aggregation based on group by

Month
1     6500.0
3    29000.0
Name: Salary, dtype: float64

In [79]:
df.groupby('Month').agg({'Salary':'mean','Name':'count'})

        Salary  Name
Month
1       6500.0     2
3      29000.0     1

#10.Concatenate and merge Dataframe (JOINS)

In [81]:
df1= pd.DataFrame({'ID':[1,2,3],'Name':['A',"B","C"]})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [83]:
df2=pd.DataFrame({'ID':[1,2,2,3],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   3     79

In [85]:
pd.concat([df1,df2],axis=1)    #Vertical /row level /top on top

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   3     79

In [86]:
#JOINS -----> Merge
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   3    C     79

In [87]:
pd.merge(df1,df2,how='inner',left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   3    C     79